language: r
sudo: required

before_install:
  - chmod 755 ./.push_gh_pages.sh
    
apt_packages:
 - libxml2-dev

r_github_packages:
 - Rdatatable/data.table
 - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - ./.push_gh_pages.sh
